/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as AdminXpEventsRouteImport } from './routes/admin/xp-events'
import { Route as AdminVenuesRouteImport } from './routes/admin/venues'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTranslationsRouteImport } from './routes/admin/translations'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPhotosRouteImport } from './routes/admin/photos'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminGuessesRouteImport } from './routes/admin/guesses'
import { Route as AdminGameModesRouteImport } from './routes/admin/game-modes'
import { Route as AdminDailyChallengesRouteImport } from './routes/admin/daily-challenges'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminXpEventsRoute = AdminXpEventsRouteImport.update({
  id: '/xp-events',
  path: '/xp-events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosRoute = AdminPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuessesRoute = AdminGuessesRouteImport.update({
  id: '/guesses',
  path: '/guesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameModesRoute = AdminGameModesRouteImport.update({
  id: '/game-modes',
  path: '/game-modes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDailyChallengesRoute = AdminDailyChallengesRouteImport.update({
  id: '/daily-challenges',
  path: '/daily-challenges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/daily': typeof DailyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRouteWithChildren
  '/upload': typeof UploadRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/daily-challenges': typeof AdminDailyChallengesRoute
  '/admin/game-modes': typeof AdminGameModesRoute
  '/admin/guesses': typeof AdminGuessesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/admin/xp-events': typeof AdminXpEventsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily': typeof DailyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/upload': typeof UploadRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/daily-challenges': typeof AdminDailyChallengesRoute
  '/admin/game-modes': typeof AdminGameModesRoute
  '/admin/guesses': typeof AdminGuessesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/admin/xp-events': typeof AdminXpEventsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/daily': typeof DailyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRouteWithChildren
  '/upload': typeof UploadRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/daily-challenges': typeof AdminDailyChallengesRoute
  '/admin/game-modes': typeof AdminGameModesRoute
  '/admin/guesses': typeof AdminGuessesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/photos': typeof AdminPhotosRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/admin/xp-events': typeof AdminXpEventsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/daily'
    | '/leaderboard'
    | '/login'
    | '/play'
    | '/profile'
    | '/upload'
    | '/admin/ads'
    | '/admin/daily-challenges'
    | '/admin/game-modes'
    | '/admin/guesses'
    | '/admin/integrations'
    | '/admin/moderation'
    | '/admin/photos'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/venues'
    | '/admin/xp-events'
    | '/profile/edit'
    | '/admin/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily'
    | '/leaderboard'
    | '/login'
    | '/play'
    | '/upload'
    | '/admin/ads'
    | '/admin/daily-challenges'
    | '/admin/game-modes'
    | '/admin/guesses'
    | '/admin/integrations'
    | '/admin/moderation'
    | '/admin/photos'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/venues'
    | '/admin/xp-events'
    | '/profile/edit'
    | '/admin'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/daily'
    | '/leaderboard'
    | '/login'
    | '/play'
    | '/profile'
    | '/upload'
    | '/admin/ads'
    | '/admin/daily-challenges'
    | '/admin/game-modes'
    | '/admin/guesses'
    | '/admin/integrations'
    | '/admin/moderation'
    | '/admin/photos'
    | '/admin/settings'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/venues'
    | '/admin/xp-events'
    | '/profile/edit'
    | '/admin/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DailyRoute: typeof DailyRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/xp-events': {
      id: '/admin/xp-events'
      path: '/xp-events'
      fullPath: '/admin/xp-events'
      preLoaderRoute: typeof AdminXpEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/venues': {
      id: '/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos': {
      id: '/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AdminPhotosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guesses': {
      id: '/admin/guesses'
      path: '/guesses'
      fullPath: '/admin/guesses'
      preLoaderRoute: typeof AdminGuessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game-modes': {
      id: '/admin/game-modes'
      path: '/game-modes'
      fullPath: '/admin/game-modes'
      preLoaderRoute: typeof AdminGameModesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/daily-challenges': {
      id: '/admin/daily-challenges'
      path: '/daily-challenges'
      fullPath: '/admin/daily-challenges'
      preLoaderRoute: typeof AdminDailyChallengesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminDailyChallengesRoute: typeof AdminDailyChallengesRoute
  AdminGameModesRoute: typeof AdminGameModesRoute
  AdminGuessesRoute: typeof AdminGuessesRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPhotosRoute: typeof AdminPhotosRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
  AdminXpEventsRoute: typeof AdminXpEventsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminDailyChallengesRoute: AdminDailyChallengesRoute,
  AdminGameModesRoute: AdminGameModesRoute,
  AdminGuessesRoute: AdminGuessesRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPhotosRoute: AdminPhotosRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVenuesRoute: AdminVenuesRoute,
  AdminXpEventsRoute: AdminXpEventsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DailyRoute: DailyRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRouteWithChildren,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
